<div class="container">
    <div class="row">
        <div class="user-data">
            <h3>User data</h3>
            <p>User name: <span><?php echo $data['name'];?></span></p>
            <p>User email: <span><?php echo $data['email'];?></span></p>
        </div>
        <div class="buttons-list">
            <a href="/logout" class="btn btn-default">Logout</a>
        </div>
    </div>
</div>