<div class="container">
    <div class="row clearfix">
        <div class="col-lg-6 col-lg-offset-3">
            <h2 class="text-center">Login Form</h2>
            <?php if (isset($data)):?>
                <div class="alert alert-danger">
                    <?php foreach ($data as $error):?>
                        <p><?php echo $error;?></p>
                    <?php endforeach;?>
                </div>
            <?php endif?>
            <form action="#" method="post">
                <div class="form-group">
                    <label for="email">Email or Login:</label>
                    <input type="text" name="data" class="form-control" id="email">
                </div>
                <div class="form-group">
                    <label for="pwd">Password:</label>
                    <input type="password" name="password" class="form-control" id="pwd">
                </div>
                <button type="submit" name="submit" class="btn btn-success">Submit</button>
                <a href="register" class="btn btn-default">Registration</a>
            </form>
        </div>
    </div>
</div>