<div class="container">
    <div class="row clearfix">
        <div class="col-lg-6 col-lg-offset-3">
            <h2 class="text-center">Registration Form</h2>

            <?php if (isset($data['errors'])):?>
            <div class="alert alert-danger">
                    <?php foreach ($data['errors'] as $error):?>
                        <p><?php echo $error;?></p>
                    <?php endforeach;?>
            </div>
            <?php endif?>
            <form method="post" action="#">
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="email" class="form-control" id="email">
                </div>
                <div class="form-group">
                    <label for="login">Login:</label>
                    <input type="text" name="login" class="form-control" id="login">
                </div>
                <div class="form-group">
                    <label for="name">Username:</label>
                    <input type="text" name="name" class="form-control" id="name">
                </div>
                <div class="form-group">
                    <label for="pwd">Password:</label>
                    <input type="password" name="password" class="form-control" id="pwd">
                </div>
                <div class="form-group">
                    <label for="sel1">Select country:</label>
                    <select class="form-control" id="sel1" name="country">
                        <?php foreach ($data['countries'] as $item):?>
                            <option value="<?php echo $item['id'];?>"><?php echo $item['name']?></option>
                        <?php endforeach;?>
                    </select>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" name="conditions"> Conditions</label>
                </div>
                <button type="submit" class="btn btn-success" name="submit">Submit</button>
            </form>
        </div>
    </div>
</div>